version: "3.8"
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: spring

    mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - servletReactive
    hostname: db

  servlet:
    environment:
      DSURL: jdbc:postgresql://localhost:5432/postgres
      DSCLASS: org.postgresql.Driver

networks:
  servletReactive:
    name: servletReactive
    driver: bridge
