version: "3.8"
services:
  db:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/neo4j:/var/lib/neo4j/data
    restart: always
    networks:
      - servletReactive
    hostname: db

#  servlet:
#    environment:
#      DSURL: jdbc:postgresql://db:5432/postgres
#      DSCLASS: org.postgresql.Driver
#      R2DBC_URL: r2dbc:postgresql://db:5432/postgres

networks:
  servletReactive:
    name: servletReactive
    driver: bridge
