version: "3.8"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: spring
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - servletReactive
    hostname: db

  servlet:
    environment:
      DSURL: jdbc:postgresql://localhost:5432/postgres
      DSCLASS: org.postgresql.Driver

networks:
  servletReactive:
    name: servletReactive
    driver: bridge
