version: "3.8"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: spring
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - servletReactive
    hostname: db
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "4GB"
        reservations:
          cpus: "0.4"
          memory: "4GB"

  servlet:
    environment:
      DSURL: jdbc:postgresql://postgres:5432/postgres
      DSCLASS: org.postgresql.Driver
      PROFILE: postgres


  reactive:
    environment:
      R2DBC_URL: r2dbc:postgresql://postgres:5432/postgres
      PROFILE: postgres


networks:
  servletReactive:
    name: servletReactive
    driver: bridge
