version: "3.8"
services:
  reactive:
    build: Reactive/
    ports:
      - "8081:8080"
      - "8850:8849"
    networks:
      - servletReactive
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "4GB"
        reservations:
          cpus: "0.5"
          memory: "4GB"




networks:
  servletReactive:
    external: true
